### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [bdraco/discovery30303#1]
**Is your feature request related to a problem? Please describe.**
Only a wheel is available on PyPI.

**Describe the solution you'd like**
Please tag the source. Thanks

**Additional context**
Packages for distributions are usually build out of the source.

**Comment by bdraco** [comment]
I just checked and the tags are there https://github.com/bdraco/discovery30303/tags

```
discovery30303 % git push upstream-rw master --tag
Everything up-to-date
```

I don't see anything missing

**Comment by fabaff** [comment]
Sorry, I don't know where I was checking...
